# python-api-challenge
note that i screwed up and accidentally published an api key.  i deleted that repo which had 5 commits to this.
